spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: client
                          uri: lb://client
                          predicates:
                              - Path=/client/**
                        - id: engagement
                          uri: lb://engagement
                          predicates:
                              - Path=/engagement/**
                          filters:
                              - StripPrefix=1
                        - id: staffing
                          uri: lb://staffing
                          predicates:
                              - Path=/staffing/**
                          filters:
                              - StripPrefix=1

server:
    port: 8125
    servlet:
        session:
            cookie:
                same-site: none
                secure: true

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
        registry-fetch-interval-seconds: 5
    instance:
        hostname: localhost
        ip-address: 127.0.0.1
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        leaseRenewalIntervalInSeconds: 10
