cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://du83k7mttey3e.cloudfront.net,https://d1r0oi9vzejxs3.cloudfront.net}

spring:
    application:
        name: api-gateway
    output:
        ansi:
            enabled: always
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: client
                          uri: lb://client
                          predicates:
                              - Path=/client/**
                          filters:
                              - StripPrefix=1
                        - id: engagement
                          uri: lb://engagement
                          predicates:
                              - Path=/engagement/**
                          filters:
                              - StripPrefix=1
                        - id: staffing
                          uri: lb://staffing
                          predicates:
                              - Path=/staffing/**
                          filters:
                              - StripPrefix=1

server:
    port: 8125
    servlet:
        session:
            cookie:
                same-site: none
                secure: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,gateway

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka/