spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: engagement

    output:
        ansi:
            enabled: always

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            mode: always

    security:
        oauth2:
            resourceserver:
                jwt:
                    public-key-location: classpath:keys/public.pem

    config:
        import: optional:file:.env[.properties]

server:
    port: 8082

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
<<<<<<< HEAD
            default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}
        registry-fetch-interval-seconds: 5

    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        leaseRenewalIntervalInSeconds: 10
=======
            defaultZone: http://localhost:8761/eureka/
        registry-fetch-interval-seconds: 5
>>>>>>> aws-preauth
