spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: engagement

    output:
        ansi:
            enabled: always

    datasource:
        url: ${CLIENT_DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            mode: always
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: false

notification:
    kafka:
        topic: notification.events

    security:
        oauth2:
            resourceserver:
                jwt:
                    public-key-location: classpath:keys/public.pem

server:
    port: 8082

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
        registry-fetch-interval-seconds: 5

    instance:
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 10
