-- Reset seed data on every startup so local/dev environments stay consistent
TRUNCATE TABLE engagements RESTART IDENTITY CASCADE;

INSERT INTO engagements (engagement_name, client_id, engagement_type, summary, start_date, target_end_date, status, is_active) VALUES
('Q3 Enterprise Risk Audit', 1, 'Audit', 'Comprehensive review of enterprise risk controls and financial reporting processes ahead of year-end close.', '2026-06-01', '2026-09-30', 'In Progress', TRUE),
('Tax Optimization & Compliance Review', 1, 'Tax Advisory', 'Assessment of tax positions and filing processes to identify optimization opportunities and ensure regulatory compliance.', '2026-07-15', '2026-11-15', 'In Progress', TRUE),
('Supply Chain Cloud Migration Risk', 2, 'Risk Consulting', 'Risk-focused guidance for migrating supply chain systems to a cloud-based infrastructure.', '2026-05-01', '2026-10-31', 'In Progress', TRUE),
('Cybersecurity Risk Assessment', 3, 'Risk Consulting', 'Evaluation of network, application, and data security controls to identify vulnerabilities and recommend remediations.', '2026-08-01', '2026-12-15', 'Planned', TRUE),
('ESG Financial Strategy Advisory', 4, 'Financial Advisory', 'Advisory engagement to align financial strategy with environmental, social, and governance reporting goals.', '2026-09-01', '2027-02-28', 'Planned', TRUE),
('Legacy Systems Decommissioning Audit', 5, 'Audit', 'Audit of decommissioning procedures for legacy systems to confirm data retention and compliance requirements were met.', '2025-01-10', '2025-06-30', 'Completed', TRUE),
('Vanguard Internal Controls Audit', 2, 'Audit', 'Evaluation of internal control design and operating effectiveness across core financial processes.', '2025-03-01', '2025-08-15', 'Completed', TRUE),
('BlackRock Tax Structuring Advisory', 3, 'Tax Advisory', 'Advisory on entity structuring and cross-border tax positions.', '2026-02-01', '2026-07-31', 'Completed', TRUE),
('Schwab M&A Due Diligence', 4, 'Financial Advisory', 'Financial and operational due diligence supporting a prospective acquisition.', '2026-10-01', '2027-01-31', 'Planned', TRUE),
('PNC Regulatory Compliance Audit', 5, 'Audit', 'Audit of regulatory compliance program effectiveness following a prior-year exam finding.', '2024-09-01', '2025-02-28', 'Completed', TRUE),
('Northwell Health Claims Audit', 6, 'Audit', 'Audit of claims processing controls and reimbursement accuracy.', '2026-04-01', '2026-09-15', 'In Progress', TRUE),
('Northwell Revenue Cycle Advisory', 6, 'Financial Advisory', 'Advisory engagement to improve revenue cycle performance and reduce denial rates.', '2026-11-01', '2027-03-31', 'Planned', TRUE),
('CVS Health Risk Consulting', 7, 'Risk Consulting', 'Enterprise risk assessment across pharmacy and retail operations.', '2026-06-15', '2026-12-31', 'In Progress', TRUE),
('CVS Tax Advisory Engagement', 7, 'Tax Advisory', 'Review of state and local tax positions across retail locations.', '2025-05-01', '2025-10-31', 'Completed', TRUE),
('Delta Fleet Financial Audit', 8, 'Audit', 'Audit of fleet asset valuation and depreciation methodology.', '2026-07-01', '2026-11-30', 'In Progress', TRUE),
('Delta Fuel Hedging Risk Advisory', 8, 'Risk Consulting', 'Risk assessment of fuel hedging strategy and counterparty exposure.', '2026-01-15', '2026-06-30', 'Completed', TRUE),
('Union Pacific Rail Safety Risk Review', 9, 'Risk Consulting', 'Review of rail safety risk controls and incident response readiness.', '2026-09-15', '2027-01-15', 'Planned', TRUE),
('P&G Tax Compliance Review', 10, 'Tax Advisory', 'Review of multi-jurisdictional tax compliance processes.', '2026-03-01', '2026-08-31', 'In Progress', TRUE),
('P&G Supply Chain Financial Advisory', 10, 'Financial Advisory', 'Advisory on supply chain financing and working capital optimization.', '2025-11-01', '2026-04-30', 'Completed', TRUE),
('Kraft Heinz Divestiture Audit', 11, 'Audit', 'Carve-out financial statement audit supporting a brand divestiture.', '2024-06-01', '2024-12-31', 'Completed', TRUE),
('Duke Energy Regulatory Audit', 12, 'Audit', 'Audit of rate-case regulatory filings and supporting cost documentation.', '2026-05-15', '2026-10-15', 'In Progress', TRUE),
('Duke Energy Risk Consulting', 12, 'Risk Consulting', 'Risk assessment of grid modernization program.', '2026-12-01', '2027-04-30', 'Planned', TRUE),
('NextEra Energy Tax Advisory', 13, 'Tax Advisory', 'Advisory on renewable energy tax credit eligibility.', '2026-09-01', '2027-01-31', 'Planned', TRUE),
('Salesforce Internal Audit', 14, 'Audit', 'Internal audit of revenue recognition controls under ASC 606.', '2026-02-15', '2026-07-15', 'Completed', TRUE),
('Salesforce Risk Consulting Engagement', 14, 'Risk Consulting', 'Third-party vendor risk assessment program.', '2026-07-20', '2026-12-20', 'In Progress', TRUE),
('Adobe Financial Advisory Engagement', 15, 'Financial Advisory', 'Advisory on capital allocation strategy and M&A pipeline evaluation.', '2026-10-15', '2027-03-15', 'Planned', TRUE),
('Adobe Tax Structuring Review', 15, 'Tax Advisory', 'Review of global tax structuring following recent acquisitions.', '2025-08-01', '2026-01-31', 'Completed', TRUE),
('Fidelity Digital Assets Risk Review', 1, 'Risk Consulting', 'Risk assessment of digital asset custody and trading controls.', '2026-01-01', '2026-05-31', 'Completed', TRUE),
('Vanguard ESG Reporting Advisory', 2, 'Financial Advisory', 'Advisory on ESG disclosure alignment with emerging reporting standards.', '2026-08-15', '2027-01-15', 'In Progress', TRUE),
('BlackRock Cybersecurity Audit', 3, 'Audit', 'Audit of cybersecurity control design across trading platforms.', '2026-11-01', '2027-04-30', 'Planned', TRUE),
('Schwab Cloud Migration Risk Review', 4, 'Risk Consulting', 'Risk review of a planned cloud migration, paused pending vendor selection.', '2026-04-01', '2026-09-30', 'Cancelled', TRUE),
('PNC Compliance Review', 5, 'Tax Advisory', 'Review of tax withholding compliance processes, currently on hold pending client resourcing.', '2026-06-01', '2026-11-30', 'On Hold', TRUE);
