-- Reset seed data on every startup so local/dev environments stay consistent
--TRUNCATE TABLE assignments, consultants RESTART IDENTITY CASCADE;

-- INSERT INTO consultants (name, title_role, primary_skill_area, user_id, is_active) VALUES
-- ('Gina Vance', 'Senior Associate', 'Technology', 'user_gina_vance', TRUE),
-- ('David Sterling', 'Manager', 'Audit', 'user_david_sterling', TRUE),
-- ('Aisha Patel', 'Senior Consultant', 'Tax', 'user_aisha_patel', TRUE),
-- ('Liam O''Connor', 'Risk Analyst', 'Risk', 'user_liam_oconnor', TRUE),
-- ('Chloe Zhao', 'Engagement Manager', 'Strategy', 'user_chloe_zhao', TRUE);

-- INSERT INTO assignments (consultant_id, engagement_id, engagement_role, assignment_start_date, is_active) VALUES
-- -- Gina assigned to Supply Chain Cloud Migration as Senior Associate
-- (1, 3, 'Senior Associate', '2026-05-01', TRUE),
-- -- Gina assigned to Q3 Enterprise Risk Audit as Associate
-- (1, 1, 'Associate', '2026-06-01', TRUE),
-- -- David Sterling (Manager/Lead) on Q3 Enterprise Risk Audit
-- (2, 1, 'Lead', '2026-06-01', TRUE),
-- -- Aisha Patel on Tax Optimization
-- (3, 2, 'Lead', '2026-07-15', TRUE),
-- -- Liam O''Connor on Cybersecurity Risk Assessment
-- (4, 4, 'Senior Associate', '2026-08-01', TRUE),
-- -- Chloe Zhao managing ESG Financial Strategy
-- (5, 5, 'Lead', '2026-09-01', TRUE);
