spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: client
    output:
        ansi:
            enabled: always
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
    sql:
        init:
            mode: always

server:
    port: 8081

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        registry-fetch-interval-seconds: 5
    instance:
        instance-id: ${spring.application.name}:${server.port}
        leaseRenewalIntervalInSeconds: 10

---
spring:
    config:
        activate:
            on-profile: default

eureka:
    client:
        service-url:
            defaultZone: http://client-platform-eureka-env.us-east-1.elasticbeanstalk.com/eureka/
        registry-fetch-interval-seconds: 5
